In [1]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
steps = [('StandardScaler', StandardScaler()),
         ('classifier', LogisticRegression())]

In [3]:
steps

[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

In [4]:
pipe = Pipeline(steps)


In [5]:
pipe

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [6]:
Pipeline
[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [9]:
X.shape

(1000, 20)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
X_train

array([[ 1.40192034e-01,  3.56179408e-02,  1.20099334e-01, ...,
         5.54564186e-01, -1.76884751e+00,  4.47885689e-01],
       [-9.41171034e-01, -2.47485265e-01, -1.57597861e-01, ...,
         1.02951824e+00,  3.04810796e+00,  4.67064009e-01],
       [ 4.63479052e-01, -2.56573387e+00,  2.74490039e-03, ...,
        -1.04399754e+00, -1.19852428e+00, -3.27235341e-01],
       ...,
       [ 4.94167029e-01, -1.63134893e+00, -2.19267145e-01, ...,
         1.09321520e+00,  2.44001844e+00,  1.85558159e+00],
       [-2.47244205e+00, -4.85866762e-01, -1.66844603e-01, ...,
         1.18125272e+00, -1.29599654e+00, -1.30133163e+00],
       [-1.65261734e+00,  5.73473685e-02, -1.59834127e+00, ...,
        -2.02398652e+00, -1.94481897e+00,  8.32439028e-01]])

In [12]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [13]:
y_pred=pipe.predict(X_test)

In [14]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1])

In [15]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [16]:
steps = [('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('SVC', SVC())]

In [17]:
pipe2 = Pipeline(steps)

In [18]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('SVC', SVC())])

In [19]:
y_pred_svc = pipe2.predict(X_test)
y_pred_svc

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1])

In [21]:
from sklearn.impute import SimpleImputer

In [22]:
import numpy as np
numeric_processor = Pipeline(steps=[
    ('imputation_mean', SimpleImputer(missing_values=np.nan,strategy='mean')),
    ('scaler', StandardScaler())
])

In [23]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [24]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(steps=[{"imputation_constant", SimpleImputer(fill_value='missing',strategy='constant')},
                                        ('onehot', OneHotEncoder(handle_unknown='ignore'))])


In [25]:
categorical_processor

Pipeline(steps=[{SimpleImputer(fill_value='missing', strategy='constant'),
                 'imputation_constant'},
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [26]:
from sklearn.compose import ColumnTransformer

In [27]:
preprocessor = ColumnTransformer(
    transformers=[[("categorical", categorical_processor, ['gender', 'City']),
                   ("numerical", numeric_processor, ['Age', 'Height'])
                   ]])

In [28]:
from sklearn.pipeline import make_pipeline

In [29]:
pipe = make_pipeline(preprocessor, LogisticRegression())

In [30]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[[('categorical',
                                                   Pipeline(steps=[{SimpleImputer(fill_value='missing',
                                                                                  strategy='constant'),
                                                                    'imputation_constant'},
                                                                   ('onehot',
                                                                    OneHotEncoder(handle_unknown='ignore'))]),
                                                   ['gender', 'City']),
                                                  ('numerical',
                                                   Pipeline(steps=[('imputation_mean',
                                                                    SimpleImputer()),
                                                                   ('scaler',
                                                                    StandardScaler())]),
                                                   ['Age', 'Height'])]])),
                ('logisticregression', LogisticRegression())])